[terminal.shell]
program = "/opt/homebrew/bin/tmux"

[window]

padding.x = 20
padding.y = 20

decorations = "Buttonless"
option_as_alt = "Both"

[font]

normal.family = "MesloLGS Nerd Font Mono"
size = 16

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "Left", mods = "Command", chars = "\u001B[H" },
  { key = "Right", mods = "Command", chars = "\u001B[F" },
  { key = "Backspace", mods = "Command", chars = "\u0015" }
]
