
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

input {
	kb_variant = dvorak
	scroll_factor = 0.5
	natural_scroll = true
	sensitivity = -0.5
	repeat_delay = 300
}
